export const fallbackPayload = {
  generated_at: "2026-04-22",
  strategy: {
    playbook_headline: "系统会先给出几种可量化方案，你可以先选一套再继续看结果。",
    selected_playbook_id: null,
    recommended_playbook_id: "balanced_default",
    playbooks: [
      {
        id: "balanced_default",
        title: "平衡试探型",
        thesis: "先用一套中性参数把方向跑通，再决定往哪边加码。",
        fit_for: "适合想法还不够具体时先验证方向。",
        highlights: ["风险平衡", "波段持有", "先在主板验证"],
      },
      {
        id: "chip_first",
        title: "筹码优先型",
        thesis: "先把上方压力和筹码干净度放在第一位。",
        fit_for: "适合特别看重上方筹码的人。",
        highlights: ["上方压力更严", "筹码结构优先", "容忍更少噪音"],
      },
      {
        id: "trend_first",
        title: "趋势确认型",
        thesis: "先确认均线、斜率和量能，再决定是否上车。",
        fit_for: "适合偏右侧确认的人。",
        highlights: ["均线多头优先", "放量确认更严", "右侧交易"],
      },
    ],
    advice: [
      { title: "推荐市场", value: "先测主板", detail: "先把主板规则跑顺，再扩展到别的市场。" },
      { title: "上方压力", value: "4% - 6%", detail: "先用较稳的压力区间做第一轮验证。" },
      { title: "核心驱动", value: "筹码结构", detail: "先让一个主信号决定结果，再叠加其他过滤。" },
      { title: "量比门槛", value: ">= 1.8", detail: "突破型策略建议先看放量是否充足。" },
    ],
    parsed_rules: [
      { group: "系统判断", label: "当前为演示模式" },
      { group: "系统判断", label: "暂时没有读取你的实时文字约束" },
    ],
    parameters: [
      { label: "上方筹码压力", value: "4% - 6%", hint: "风险越保守，这个阈值越要收紧。" },
      { label: "放量标准", value: ">= 1.8", hint: "量比越高，突破确认通常越强。" },
      { label: "筑底时长", value: "60 - 120 天", hint: "底部整理不够，趋势持续性通常会偏弱。" },
      { label: "估值要求", value: "不过热即可", hint: "第一版可以先别把估值卡得太死。" },
    ],
    summary: "当前是稳定演示模式。后续接入更完整数据后，这里会自动切到真实扫描结果。",
  },
  results: {
    label: "主板",
    note: "当前是演示数据模式，用来保证网页流程稳定可用。",
    live_data: false,
    items: [
      {
        symbol: "600276.SH",
        market_segment: "main_board",
        trade_date: "2026-04-22",
        passed_filters: true,
        preview_mock: true,
        score: {
          total: 72.2,
          reasons: ["上方压力较小", "筑底时间较充分", "量比已经进入有效突破区间"],
        },
        failed_reasons: [],
        metrics: {
          volume_ratio: 2.06,
          overhead_pressure: 0.028,
          base_days: 102,
          winner_rate: 0.64,
          cost_5pct: 50.2,
          cost_50pct: 53.8,
          cost_95pct: 58.0,
          chip_source_label: "东方财富筹码",
          limit_up: true,
          relimit: false,
          broken_limit: false,
          first_limit_time: "09:43:00",
          last_limit_time: "14:28:00",
          limit_open_times: 0,
          limit_reason: "医药",
          limit_source_label: "东方财富涨停池",
        },
      },
      {
        symbol: "600036.SH",
        market_segment: "main_board",
        trade_date: "2026-04-21",
        passed_filters: false,
        preview_mock: false,
        score: {
          total: 58.85,
          reasons: ["筹码相对集中", "筑底周期较完整"],
        },
        failed_reasons: ["放量确认不足", "突破信号还不够明确"],
        metrics: {
          volume_ratio: 0.8919,
          overhead_pressure: 0.0464,
          base_days: 120,
          winner_rate: 0.58,
          cost_5pct: 40.5,
          cost_50pct: 42.7,
          cost_95pct: 46.1,
          chip_source_label: "东方财富筹码",
          limit_up: false,
          relimit: false,
          broken_limit: false,
          first_limit_time: "",
          last_limit_time: "",
          limit_open_times: 0,
          limit_reason: "",
          limit_source_label: "涨跌幅估算",
        },
      },
      {
        symbol: "600519.SH",
        market_segment: "main_board",
        trade_date: "2026-04-21",
        passed_filters: false,
        preview_mock: false,
        score: {
          total: 43.51,
          reasons: ["筹码结构尚可", "底部整理时间够长"],
        },
        failed_reasons: ["均线结构还没完全转强", "量比依然偏弱"],
        metrics: {
          volume_ratio: 0.6801,
          overhead_pressure: 0.0657,
          base_days: 120,
          winner_rate: 0.55,
          cost_5pct: 1490.0,
          cost_50pct: 1530.0,
          cost_95pct: 1684.0,
          chip_source_label: "近似筹码",
          limit_up: false,
          relimit: false,
          broken_limit: false,
          first_limit_time: "",
          last_limit_time: "",
          limit_open_times: 0,
          limit_reason: "",
          limit_source_label: "涨跌幅估算",
        },
      },
    ],
  },
  market_review: {
    trade_date: "2026-04-22",
    live_data: false,
    headline: "演示复盘：资金偏向低位防守和能源方向，高位题材有分歧。",
    note: "当前为演示资金流，用来保证页面流程稳定。",
    top_inflow: [
      { name: "电力", change_pct: 0.8, net_inflow: 1620000000, net_inflow_text: "16.2亿", source: "演示行业资金" },
      { name: "煤炭", change_pct: 1.1, net_inflow: 980000000, net_inflow_text: "9.8亿", source: "演示行业资金" },
      { name: "中特估", change_pct: 0.9, net_inflow: 890000000, net_inflow_text: "8.9亿", source: "演示概念资金" },
    ],
    top_outflow: [
      { name: "算力", change_pct: 3.4, net_inflow: -1250000000, net_inflow_text: "-12.5亿", source: "演示概念资金" },
      { name: "低空经济", change_pct: 4.2, net_inflow: -930000000, net_inflow_text: "-9.3亿", source: "演示概念资金" },
      { name: "半导体", change_pct: 2.2, net_inflow: -860000000, net_inflow_text: "-8.6亿", source: "演示行业资金" },
    ],
    rotation: {
      summary: "出现高切低迹象：部分涨幅较高方向流出，低位或涨幅较小方向承接资金。",
      low_level_inflow: [
        { name: "电力", change_pct: 0.8, net_inflow: 1620000000, net_inflow_text: "16.2亿", source: "演示行业资金" },
        { name: "煤炭", change_pct: 1.1, net_inflow: 980000000, net_inflow_text: "9.8亿", source: "演示行业资金" },
      ],
      high_level_outflow: [
        { name: "算力", change_pct: 3.4, net_inflow: -1250000000, net_inflow_text: "-12.5亿", source: "演示概念资金" },
        { name: "低空经济", change_pct: 4.2, net_inflow: -930000000, net_inflow_text: "-9.3亿", source: "演示概念资金" },
      ],
    },
  },
  backtest: {
    hold_days: 15,
    stop_loss: "-7%",
    take_profit: "18%",
    max_positions: 10,
  },
};
